import React from 'react';
import Head from 'next/head';
import img1 from '../assets/images/5.png';
import img2 from '../assets/images/6.png';
import img3 from '../assets/images/7.png';
import FastFoodCard from '../components/card/FastFood';
import Banner from '../components/banner/Banner';
import FoodCard from '../components/card/Food';
import Button from '../components/button/Button';
import ServiceCard from '../components/card/Service';
import foodImage from '../assets/images/steak.png';
import foodImage2 from '../assets/images/pasta.png';
import foodImage3 from '../assets/images/spagettie.png';

const serviceList: ServiceProps[] = [
  {
    iconName: 'priceTag',
    title: 'Discount system',
    description: 'We have favorable discount system for our regular customer',
  },
  {
    iconName: 'delivery',
    title: 'Delivery',
    description: 'Fast and safe delivery from us with a reliable introduction',
  },
  {
    iconName: 'tray',
    title: '500+ Restaurant ',
    description: 'We have more then 500 thousand restaurant who cooperate with us',
  },
  {
    iconName: 'winner',
    title: 'Best quality',
    description: 'We provide the best service and high quality',
  },
];

const foodList: FoodProps[] = [
  {
    id: 1,
    title: 'Steak',
    featuredImageUrl: foodImage,
    description: 'Mô tả',
    place: 'Hồ Chí Minh',
  },
  {
    id: 2,
    title: 'Steak',
    featuredImageUrl: foodImage2,
    description: 'Mô tả',
    place: 'Hồ Chí Minh',
  },
  {
    id: 3,
    title: 'Steak',
    featuredImageUrl: foodImage3,
    description: 'Mô tả',
    place: 'Hồ Chí Minh',
  },
];
export default function Home() {
  return (
    <>
      <Head>
        <title>Food Delivery App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Banner />
      <section id='why-fast-food' className='why-fast-food'>
        <div className='section__heading'>
          <h2 className='section__title'>Why fast food ?</h2>
        </div>
        <ul className='fast-food-list'>
          <li className='fast-food-item'>
            <FastFoodCard
              imgUrl={img1}
              imgAlt='Fast food is easy'
              title='Easy'
              description='Only with your smartphone you can get a food'
            />
          </li>
          <li className='fast-food-item'>
            <FastFoodCard
              imgUrl={img2}
              imgAlt='Fast food is fast'
              title='Fast'
              description='We can deliver your food
              very fast'
            />
          </li>
          <li className='fast-food-item'>
            <FastFoodCard
              imgUrl={img3}
              imgAlt='Fast food is saft'
              title='Safe'
              description='All food label halal and stay
              healthy for you'
            />
          </li>
        </ul>
      </section>
      <section id='food' className='food'>
        <div className='section__heading'>
          <h2 className='section__title'>Food</h2>
          <div className='section__sub-title'>Top restaurant for dining out or in !</div>
        </div>
        <div className='section__content'>
          <ul className='food-list'>
            {Array.from(foodList).map(food => {
              return (
                <li key={food.id} className='food-item'>
                  <FoodCard {...food} />
                </li>
              );
            })}
          </ul>
          <div className='text-center'>
            <Button className='food__food-more'>Food more</Button>
          </div>
        </div>
      </section>
      <section>
        <div className='section__heading'>
          <h2 className='section__title'>Services</h2>
          <div className='section__sub-title'>Service from our services to you</div>
        </div>
        <div className='section__content section__content--services'>
          <div className='service__right flex flex-col w-full md:w-[calc(60%)]'>
            <ul className='service-list flex flex-row flex-wrap'>
              {serviceList?.map((service, index) => {
                return (
                  <li key={index} className='flex flex-col w-full md:w-[calc(50%-2rem)] m-2 md:m-4'>
                    <ServiceCard iconName={service.iconName} title={service.title} description={service.description} />
                  </li>
                );
              })}
            </ul>
          </div>
        </div>
      </section>
      <section>
        <div className='section__heading'>
          <h2 className='section__title'>About Us</h2>
          <div className='section__sub-title'>Resume about our company</div>
        </div>
        <div className='section__content section__content--about-us'>
          <div className='about-us__left'>
            <p>
              We are company engaged in the field food services with a very wide range throughout indonesia. we work
              closely with more than 500+ restaurant in indonesia
            </p>
            <div className='mt-[50px]'>
              <Button size='lg'>Read more</Button>
            </div>
          </div>
        </div>
      </section>
      <section>
        <div className='section__heading'>
          <h2 className='section__title'>Contact Us</h2>
          <div className='section__sub-title'>If you need a help, we can ready here</div>
        </div>
        <div className='section__content section__content--contact-us'>
          <div className='contact-us__left'>
            <p className='contact-us__title'>Let&apos;s talk</p>
            <p className='contact-us__description'>Ask us anything or just say hi..</p>
          </div>
          <div className='contact-us__right'>
            <form id='contact-us__form' className='contact-us__form'>
              <div className='input-field w-full md:w-[calc(50%-2rem)] m-4 mb-[80px]'>
                <label htmlFor='name' className='uppercase'>
                  Name
                </label>
                <input type='text' id='name' name='name' placeholder='Your name' className='input' />
              </div>
              <div className='input-field w-full md:w-[calc(50%-2rem)] m-4 mb-[80px]'>
                <label htmlFor='email' className='uppercase'>
                  Email
                </label>
                <input type='email' id='email' name='email' placeholder='example@yourdomain' className='input' />
              </div>
              <div className='input-field w-full md:w-[calc(100%-2rem)] m-4 mb-[80px]'>
                <label htmlFor='message' className='uppercase'>
                  Message
                </label>
                <input type='text' id='message' name='message' placeholder='Hi there' className='input' />
              </div>
              <div className='px-4'>
                <Button size='lg'>Send</Button>
              </div>
            </form>
          </div>
        </div>
      </section>
    </>
  );
}
